import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { BaseLayout } from '@/components/layout/base-layout.component';
import { Provider } from '@/lib/auth/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider>
          <BaseLayout>{children}</BaseLayout>
        </Provider>
      </body>
    </html>
  );
}
